POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer <token tähän>
{
    "title": "Uutta testiä kehiin",
    "author": "Kaisa Juhola",
    "url": "https://fullstackopen.com/osa4/token_perustainen_kirjautuminen",
    "likes": 156,
    "userId": "6a9d720dbed778eeb79007a5"
}
